# Generated by Django 3.2.9 on 2021-11-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='無題', max_length=255)),
                ('creator', models.CharField(blank=True, default='名無しさん', max_length=15, null=True)),
                ('view', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keijiban.category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPaddress', models.GenericIPAddressField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='名無しさん', max_length=15)),
                ('body', models.TextField(max_length=255)),
                ('tags', models.ManyToManyField(blank=True, to='keijiban.Tag')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keijiban.thread')),
            ],
        ),
    ]
